version: '3'
services:
  server:
    container_name: server
    build: 
      context: ./backend
    ports:
      - "8080:8080"
  
  front:
    container_name: front
      build:
        context: ./frontend
        restart: always
        depends_on:
          - server
        ports:
          - "80:80"
        
