spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k5f001.p.ssafy.io:3306/ssurbar?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    
spa:
  default-file: /dist/index.html
